import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

const geistSans = Inter({
 variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Inter({
 variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DataTable App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
